server:
  port: 8085

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  application:
    name: student-profile
  cloud:
    azure:
      active-directory:
        enabled: true
        credential:
          client-id: a893e8f3-2b7d-4b93-8a33-1f8645ff45ad
        profile:
          tenant-id: 8f3ee75e-0673-410f-ad7c-c7af5450489e
        app-id-uri: api://a893e8f3-2b7d-4b93-8a33-1f8645ff45ad
  datasource:
    url: jdbc:postgresql://localhost:5432/Student
    username: postgres
    password: password
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: create.sql
              create-source: metadata
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update



