create table studentprofile (student_id varchar(255) not null, dob date, dept varchar(255), level varchar(255), name varchar(255), phone varchar(255), primary key (student_id));
create table student_registration (registration_id varchar(255) not null, course_id varchar(255), course_name varchar(255), dept varchar(255), student_id varchar(255), primary key (registration_id));
create table studentprofile (student_id varchar(255) not null, dob date, dept varchar(255), level varchar(255), name varchar(255), phone varchar(255), primary key (student_id));
create table student_registration (registration_id varchar(255) not null, course_id varchar(255), course_name varchar(255), dept varchar(255), student_id varchar(255), primary key (registration_id));
create table studentprofile (student_id varchar(255) not null, dob date, dept varchar(255), level varchar(255), name varchar(255), phone varchar(255), primary key (student_id));
create table student_registration (registration_id varchar(255) not null, course_id varchar(255), course_name varchar(255), dept varchar(255), student_id varchar(255), primary key (registration_id));
create table studentprofile (student_id varchar(255) not null, dob date, dept varchar(255), level varchar(255), name varchar(255), phone varchar(255), primary key (student_id));
create table student_registration (registration_id varchar(255) not null, course_id varchar(255), course_name varchar(255), dept varchar(255), student_id varchar(255), primary key (registration_id));
create table studentprofile (student_id varchar(255) not null, dob date, dept varchar(255), level varchar(255), name varchar(255), phone varchar(255), primary key (student_id));
create table student_registration (registration_id varchar(255) not null, course_id varchar(255), course_name varchar(255), dept varchar(255), student_id varchar(255), primary key (registration_id));
create table studentprofile (student_id varchar(255) not null, dob date, dept varchar(255), level varchar(255), name varchar(255), phone varchar(255), primary key (student_id));
create table student_registration (registration_id varchar(255) not null, course_id varchar(255), course_name varchar(255), dept varchar(255), student_id varchar(255), primary key (registration_id));
create table studentprofile (student_id varchar(255) not null, dob date, dept varchar(255), level varchar(255), name varchar(255), phone varchar(255), primary key (student_id));
create table student_registration (registration_id varchar(255) not null, course_id varchar(255), course_name varchar(255), dept varchar(255), student_id varchar(255), primary key (registration_id));
create table studentprofile (student_id varchar(255) not null, dob date, dept varchar(255), level varchar(255), name varchar(255), phone varchar(255), primary key (student_id));
create table student_registration (registration_id varchar(255) not null, course_id varchar(255), course_name varchar(255), dept varchar(255), student_id varchar(255), primary key (registration_id));
create table studentprofile (student_id varchar(255) not null, dob date, dept varchar(255), level varchar(255), name varchar(255), phone varchar(255), primary key (student_id));
create table student_registration (registration_id varchar(255) not null, course_id varchar(255), course_name varchar(255), dept varchar(255), student_id varchar(255), primary key (registration_id));
